package ass

import (
	"fmt"
	"strings"
	"testing"
	"time"
)

func TestParseAndComposeASS(t *testing.T) {
	rawContent := `[Script Info]
; Script generated by test
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
; This is a comment inside events
Dialogue: 0,0:00:06.34,0:00:07.46,Default,,0,0,0,,Where is it?
Dialogue: 0,0:00:07.57,0:00:09.51,Default,,0,0,0,,I told you,\Nwe don't wear locators.
Comment: 0,0:00:10.00,0:00:11.00,Default,,0,0,0,,Internal note
Dialogue: 0,0:00:11.68,0:00:14.91,Default,Speaker,10,10,20,Scroll up,Wait.\NBig toe, left foot.
`

	file, errParse := ParseASS(rawContent)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 3 {
		t.Fatalf("expected 3 dialogues, got %d", len(dialogues))
	}

	if dialogues[0].Text != "Where is it?" {
		t.Errorf("dialogue 0 text mismatch: got %q", dialogues[0].Text)
	}
	if dialogues[0].Start != 6340*time.Millisecond {
		t.Errorf("dialogue 0 start mismatch: got %v", dialogues[0].Start)
	}
	if dialogues[0].End != 7460*time.Millisecond {
		t.Errorf("dialogue 0 end mismatch: got %v", dialogues[0].End)
	}

	if dialogues[1].Text != "I told you,\\Nwe don't wear locators." {
		t.Errorf("dialogue 1 text mismatch: got %q", dialogues[1].Text)
	}

	if dialogues[2].Name != "Speaker" || dialogues[2].MarginL != "10" || dialogues[2].Effect != "Scroll up" {
		t.Errorf("dialogue 2 fields mismatch: %+v", dialogues[2])
	}

	// Update text
	dialogues[0].SetTranslatedText("它在哪里？")

	composed := ComposeASS(file)
	if !strings.Contains(composed, "Dialogue: 0,0:00:06.34,0:00:07.46,Default,,0,0,0,,它在哪里？") {
		t.Errorf("composed output does not contain updated dialogue:\n%s", composed)
	}
	if !strings.Contains(composed, "; This is a comment inside events") {
		t.Errorf("composed output missing raw comments")
	}
	if !strings.Contains(composed, "Comment: 0,0:00:10.00,0:00:11.00,Default,,0,0,0,,Internal note") {
		t.Errorf("composed output missing comment event")
	}
}

func TestParseAndComposeASS_SectionOrder(t *testing.T) {
	rawContent := `[Script Info]
Title: Section Order Test

[V4+ Styles]
Format: Name, Fontname, Fontsize
Style: Default,Arial,16

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hello

[Fonts]
font1.ttf
`
	file, errParse := ParseASS(rawContent)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	composed := ComposeASS(file)

	// Verify section order: [Events] must come before [Fonts]
	eventsIdx := strings.Index(composed, "[Events]")
	fontsIdx := strings.Index(composed, "[Fonts]")
	dialogueIdx := strings.Index(composed, "Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hello")

	if eventsIdx == -1 || fontsIdx == -1 || dialogueIdx == -1 {
		t.Fatalf("missing sections in composed output:\n%s", composed)
	}

	if !(eventsIdx < dialogueIdx && dialogueIdx < fontsIdx) {
		t.Errorf("expected [Events] < Dialogue < [Fonts], but got events=%d, dialogue=%d, fonts=%d", eventsIdx, dialogueIdx, fontsIdx)
	}

	// Re-parse composed output and verify dialogues are still detected
	reparsed, errReparse := ParseASS(composed)
	if errReparse != nil {
		t.Fatalf("reparse failed: %v", errReparse)
	}

	dialogues := reparsed.GetDialogues()
	if len(dialogues) != 1 || dialogues[0].Text != "Hello" {
		t.Fatalf("expected 1 dialogue after roundtrip, got %d", len(dialogues))
	}
}

func TestParseASSTimestamp(t *testing.T) {
	tests := []struct {
		input    string
		expected time.Duration
		wantErr  bool
	}{
		{"0:00:06.34", 6340 * time.Millisecond, false},
		{"1:23:45.67", (1*3600+23*60+45)*time.Second + 670*time.Millisecond, false},
		{"0:00:00.00", 0, false},
		{"0:00:06,34", 6340 * time.Millisecond, false}, // comma support
		{"0:00:02.01", 2010 * time.Millisecond, false}, // critical float precision test case
		{"invalid", 0, true},
		{"1:2", 0, true},
		{"-1:00:00.00", 0, true},
		{"0:65:00.00", 0, true},
		{"0:00:65.00", 0, true},
		{"0:00:01.20.extra", 0, true},
		{"0:00:01.123junk", 0, true},
		{"0:00:00.-1", 0, true},
		{"3000000:00:00.00", 0, true},
		{"0:00:01.", 0, true},
	}

	for _, tc := range tests {
		result, err := ParseASSTimestamp(tc.input)
		if (err != nil) != tc.wantErr {
			t.Errorf("ParseASSTimestamp(%q) error = %v, wantErr %v", tc.input, err, tc.wantErr)
			continue
		}
		if !tc.wantErr && result != tc.expected {
			t.Errorf("ParseASSTimestamp(%q) = %v, expected %v", tc.input, result, tc.expected)
		}
		if tc.wantErr && err != nil && strings.Contains(err.Error(), "%!w") {
			t.Errorf("ParseASSTimestamp(%q) error contains %%!w: %v", tc.input, err)
		}
	}
}

func TestParseASSTimestamp_ErrorMessageFormatting(t *testing.T) {
	testInputs := []string{
		"0:60:00.00",
		"0:00:60.00",
		"-1:00:00.00",
		"10001:00:00.00",
	}
	for _, input := range testInputs {
		_, errParse := ParseASSTimestamp(input)
		if errParse == nil {
			t.Errorf("expected error for %s", input)
			continue
		}
		if strings.Contains(errParse.Error(), "%!w") {
			t.Errorf("error message for %s contains formatting artifact %%!w: %v", input, errParse)
		}
	}
}

func TestParseASSTimestamp_AllCentisecondsRoundtrip(t *testing.T) {
	for cs := 0; cs < 100; cs++ {
		str := fmt.Sprintf("0:00:02.%02d", cs)
		d, err := ParseASSTimestamp(str)
		if err != nil {
			t.Fatalf("ParseASSTimestamp(%s) error: %v", str, err)
		}
		formatted := FormatASSTimestamp(d)
		if formatted != str {
			t.Errorf("centisecond roundtrip mismatch: got %s, want %s (duration %v)", formatted, str, d)
		}
	}
}

func TestFormatASSTimestamp(t *testing.T) {
	tests := []struct {
		d        time.Duration
		expected string
	}{
		{6340 * time.Millisecond, "0:00:06.34"},
		{(1*3600+23*60+45)*time.Second + 670*time.Millisecond, "1:23:45.67"},
		{0, "0:00:00.00"},
		{-10 * time.Second, "0:00:00.00"},
	}

	for _, tc := range tests {
		result := FormatASSTimestamp(tc.d)
		if result != tc.expected {
			t.Errorf("FormatASSTimestamp(%v) = %q, expected %q", tc.d, result, tc.expected)
		}
	}
}

func TestParseASS_WithBOM(t *testing.T) {
	raw := "\ufeff[Script Info]\nTitle: Test\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hello\n"
	file, err := ParseASS(raw)
	if err != nil {
		t.Fatalf("ParseASS with BOM failed: %v", err)
	}
	dialogues := file.GetDialogues()
	if len(dialogues) != 1 || dialogues[0].Text != "Hello" {
		t.Errorf("unexpected dialogues: %+v", dialogues)
	}
}

func TestSplitASSTags(t *testing.T) {
	tests := []struct {
		input          string
		expectedPrefix string
		expectedClean  string
		expectedSuffix string
	}{
		{"{\\i1}They found the locator.{\\i0}", "{\\i1}", "They found the locator.", "{\\i0}"},
		{"{\\pos(192,200)}Where is it?", "{\\pos(192,200)}", "Where is it?", ""},
		{"{\\an8}{\\b1}Title{\\b0}", "{\\an8}{\\b1}", "Title", "{\\b0}"},
		{"Regular text without tags", "", "Regular text without tags", ""},
		{"{\\pos(100,200)}", "{\\pos(100,200)}", "", ""},
	}

	for _, tc := range tests {
		p, c, s := SplitASSTags(tc.input)
		if p != tc.expectedPrefix || c != tc.expectedClean || s != tc.expectedSuffix {
			t.Errorf("SplitASSTags(%q) = (%q, %q, %q), expected (%q, %q, %q)", tc.input, p, c, s, tc.expectedPrefix, tc.expectedClean, tc.expectedSuffix)
		}
	}
}

func TestDialogue_PureTagAndDrawing(t *testing.T) {
	// Pure tag line should not be translatable and should not duplicate tags
	raw := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,{\pos(100,200)}
Dialogue: 0,0:00:03.00,0:00:04.00,Default,,0,0,0,,{\p5}m 0 0 l 100 100{\p0}
Dialogue: 0,0:00:05.00,0:00:06.00,Default,,0,0,0,,{\p1}m 0 0{\p0}Normal text
Dialogue: 0,0:00:07.00,0:00:08.00,Default,,0,0,0,,{\p1\p0}Hello from normal text
Dialogue: 0,0:00:09.00,0:00:10.00,Default,,0,0,0,,{\p0\p1}m 0 0 l 50 50
Dialogue: 0,0:00:11.00,0:00:12.00,Default,,0,0,0,,{\p1\p00}Leading zero test
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 6 {
		t.Fatalf("expected 6 dialogues, got %d", len(dialogues))
	}

	if dialogues[0].IsTranslatable {
		t.Errorf("pure tag line should not be translatable")
	}
	dialogues[0].SetTranslatedText("something")
	if dialogues[0].Text != "{\\pos(100,200)}" {
		t.Errorf("pure tag line text was modified/duplicated: %q", dialogues[0].Text)
	}

	// \p5 drawing should not be translatable
	if dialogues[1].IsTranslatable {
		t.Errorf("drawing line with \\p5 should not be translatable")
	}
	dialogues[1].SetTranslatedText("something")
	if dialogues[1].Text != "{\\p5}m 0 0 l 100 100{\\p0}" {
		t.Errorf("drawing line text was modified: %q", dialogues[1].Text)
	}

	// Mixed drawing and text SHOULD be translatable, and drawing should be protected as one atomic tag
	if !dialogues[2].IsTranslatable {
		t.Errorf("mixed drawing and text line should be translatable")
	}
	dialogues[2].SetTranslatedText("[[ASSTAG0]]Translated text")
	expectedMixed := "{\\p1}m 0 0{\\p0}Translated text"
	if dialogues[2].Text != expectedMixed {
		t.Errorf("expected mixed text %q, got %q", expectedMixed, dialogues[2].Text)
	}

	// {\p1\p0}Hello: last command in tag is \p0 (off), so Hello is translatable!
	if !dialogues[3].IsTranslatable {
		t.Errorf("{\\p1\\p0}Hello should be translatable")
	}
	if !strings.Contains(dialogues[3].CleanText, "Hello from normal text") {
		t.Errorf("expected clean text to contain 'Hello from normal text', got: %q", dialogues[3].CleanText)
	}

	// {\p0\p1}Drawing: last command in tag is \p1 (on), so drawing is active and line is NOT translatable
	if dialogues[4].IsTranslatable {
		t.Errorf("{\\p0\\p1}Drawing should NOT be translatable")
	}

	// {\p1\p00}Leading zero test: \p00 is numerically 0 (off), so text IS translatable!
	if !dialogues[5].IsTranslatable {
		t.Errorf("{\\p1\\p00}Leading zero test should be translatable")
	}
}

func TestParseASS_InvalidTimestamp(t *testing.T) {
	raw := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,invalid,0:00:02.00,Default,,0,0,0,,Hello
`
	_, errParse := ParseASS(raw)
	if errParse == nil {
		t.Errorf("ParseASS should have failed on invalid start timestamp")
	}

	rawEnd := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,invalid,Default,,0,0,0,,Hello
`
	_, errParseEnd := ParseASS(rawEnd)
	if errParseEnd == nil {
		t.Errorf("ParseASS should have failed on invalid end timestamp")
	}
}

func TestParseASS_LongLine(t *testing.T) {
	// Create a line > 70 KiB to exceed the default bufio.Scanner 64 KiB buffer
	longDrawing := strings.Repeat("m 0 0 l 1 1 ", 6500) // ~78 KiB
	raw := fmt.Sprintf(`[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,{\p1}%s{\p0}
`, longDrawing)

	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed on >70 KiB line: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}
	if dialogues[0].IsTranslatable {
		t.Errorf("long drawing line should not be translatable")
	}

	composed := ComposeASS(file)
	if !strings.Contains(composed, "{\\p1}") {
		t.Errorf("composed output missing long drawing")
	}
}

func TestParseASS_MultipleEventsSections(t *testing.T) {
	raw := `[Script Info]
Title: Multiple Events

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Event 1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:03.00,0:00:04.00,Default,,0,0,0,,Event 2
`
	file, err := ParseASS(raw)
	if err != nil {
		t.Fatalf("ParseASS failed: %v", err)
	}

	composed := ComposeASS(file)

	// Count occurrences of "Event 1" and "Event 2"
	count1 := strings.Count(composed, "Event 1")
	count2 := strings.Count(composed, "Event 2")

	if count1 != 1 {
		t.Errorf("expected Event 1 to appear exactly once, got %d:\n%s", count1, composed)
	}
	if count2 != 1 {
		t.Errorf("expected Event 2 to appear exactly once, got %d:\n%s", count2, composed)
	}

	reparsed, errReparse := ParseASS(composed)
	if errReparse != nil {
		t.Fatalf("ParseASS on composed output failed: %v", errReparse)
	}
	if len(reparsed.GetDialogues()) != 2 {
		t.Fatalf("expected 2 dialogues, got %d", len(reparsed.GetDialogues()))
	}
}

func TestDialogue_InlineTagProtection(t *testing.T) {
	raw := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hello {\i1}world{\i0}!
`
	file, err := ParseASS(raw)
	if err != nil {
		t.Fatalf("ParseASS failed: %v", err)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}

	dlg := dialogues[0]
	if !dlg.IsTranslatable {
		t.Errorf("dialogue should be translatable")
	}

	// CleanText should contain placeholders protecting inline tags
	if !strings.Contains(dlg.CleanText, "[[ASSTAG0]]") || !strings.Contains(dlg.CleanText, "[[ASSTAG1]]") {
		t.Errorf("expected inline tag placeholders in CleanText: %q", dlg.CleanText)
	}

	// Simulate translated response from model
	dlg.SetTranslatedText("你好 [[ASSTAG0]]世界[[ASSTAG1]]！")
	expectedText := "你好 {\\i1}世界{\\i0}！"
	if dlg.Text != expectedText {
		t.Errorf("expected restored text %q, got %q", expectedText, dlg.Text)
	}
}

func TestDialogue_LiteralPlaceholderCollision(t *testing.T) {
	raw := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,{\i1}literal [[ASSTAG0]]{\i0}
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}

	dlg := dialogues[0]
	dlg.SetTranslatedText(dlg.CleanText)
	expectedText := "{\\i1}literal [[ASSTAG0]]{\\i0}"
	if dlg.Text != expectedText {
		t.Errorf("literal placeholder corrupted: got %q, want %q", dlg.Text, expectedText)
	}

	composed := ComposeASS(file)
	if !strings.Contains(composed, "Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,{\\i1}literal [[ASSTAG0]]{\\i0}") {
		t.Errorf("composed ASS corrupted literal placeholder:\n%s", composed)
	}
}

func TestDialogue_AtomicDrawingProtection(t *testing.T) {
	raw := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,{\p1}m 0 0 l 10 10{\p0}Hello
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}

	dlg := dialogues[0]
	if !dlg.IsTranslatable {
		t.Fatalf("dialogue with text after drawing should be translatable")
	}

	if len(dlg.Tags) != 1 {
		t.Fatalf("expected drawing block to be 1 atomic tag, got %d tags: %v", len(dlg.Tags), dlg.Tags)
	}
	if dlg.CleanText != "[[ASSTAG0]]Hello" {
		t.Errorf("expected clean text '[[ASSTAG0]]Hello', got %q", dlg.CleanText)
	}

	dlg.SetTranslatedText("[[ASSTAG0]]你好")
	expectedText := "{\\p1}m 0 0 l 10 10{\\p0}你好"
	if dlg.Text != expectedText {
		t.Errorf("restored text mismatch: got %q, want %q", dlg.Text, expectedText)
	}

	plain, ok := StripASSTagsToPlainText("{\\p1}m 0 0 l 10 10{\\p0}Hello")
	if !ok || plain != "Hello" {
		t.Errorf("StripASSTagsToPlainText failed: got (%q, %v), want (\"Hello\", true)", plain, ok)
	}
}

func TestDialogue_UnclosedDrawingAppendsP0(t *testing.T) {
	// Raw text ends in drawing mode without explicit {\p0}
	raw := `[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hello{\p1}m 0 0 l 10 10
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}

	dlg := dialogues[0]
	if !dlg.IsTranslatable {
		t.Fatalf("dialogue with text before drawing should be translatable")
	}

	// Unclosed drawing must have {\p0} appended to ensure drawing mode is closed
	if len(dlg.Tags) != 1 || dlg.Tags[0] != "{\\p1}m 0 0 l 10 10{\\p0}" {
		t.Errorf("expected tag with appended {\\p0}, got: %v", dlg.Tags)
	}
	if dlg.CleanText != "Hello[[ASSTAG0]]" {
		t.Errorf("expected clean text 'Hello[[ASSTAG0]]', got %q", dlg.CleanText)
	}

	// If model moves tag to the front, text after placeholder remains in text mode!
	dlg.SetTranslatedText("[[ASSTAG0]]你好")
	expectedText := "{\\p1}m 0 0 l 10 10{\\p0}你好"
	if dlg.Text != expectedText {
		t.Errorf("restored text mismatch: got %q, want %q", dlg.Text, expectedText)
	}

	plain, ok := StripASSTagsToPlainText(dlg.Text)
	if !ok || plain != "你好" {
		t.Errorf("StripASSTagsToPlainText failed: got (%q, %v), want (\"你好\", true)", plain, ok)
	}
}

func TestParseASS_CustomFormatFewFields(t *testing.T) {
	raw := `[Events]
Format: Start, End, Text
Dialogue: 0:00:01.00,0:00:02.00,Hello
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed on custom format: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}
	if dialogues[0].Text != "Hello" {
		t.Errorf("expected text 'Hello', got %q", dialogues[0].Text)
	}
	if dialogues[0].Start != time.Second || dialogues[0].End != 2*time.Second {
		t.Errorf("expected start 1s, end 2s, got start %v, end %v", dialogues[0].Start, dialogues[0].End)
	}

	composed := ComposeASS(file)
	if !strings.Contains(composed, "Dialogue: 0:00:01.00,0:00:02.00,Hello") {
		t.Errorf("composed output mismatch:\n%s", composed)
	}
}

func TestParseASS_CustomVendorFieldsPreserved(t *testing.T) {
	raw := `[Events]
Format: Start, End, VendorData, Text
Dialogue: 0:00:01.00,0:00:02.00,keep-me,Hello
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}
	if dialogues[0].Text != "Hello" {
		t.Errorf("expected text 'Hello', got %q", dialogues[0].Text)
	}

	composed := ComposeASS(file)
	if !strings.Contains(composed, "keep-me") {
		t.Errorf("custom field 'keep-me' was lost during ComposeASS:\n%s", composed)
	}
	if !strings.Contains(composed, "Dialogue: 0:00:01.00,0:00:02.00,keep-me,Hello") {
		t.Errorf("composed line mismatch:\n%s", composed)
	}
}

func TestParseASS_TrailingWhitespacePreserved(t *testing.T) {
	raw := "[Events]\nFormat: Start, End, Text\nDialogue: 0:00:01.00,0:00:02.00,Hello\u3000\n"
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 1 {
		t.Fatalf("expected 1 dialogue, got %d", len(dialogues))
	}
	if dialogues[0].Text != "Hello\u3000" {
		t.Errorf("trailing fullwidth space was trimmed: got %q, want %q", dialogues[0].Text, "Hello\u3000")
	}

	composed := ComposeASS(file)
	if !strings.Contains(composed, "Hello\u3000") {
		t.Errorf("composed output lost trailing whitespace:\n%q", composed)
	}
}

func TestExtractTags_PreservesLayoutEscapes(t *testing.T) {
	raw := `Top\NBottom\hWord`
	protected, tags, isTranslatable := ExtractTags(raw)
	if !isTranslatable {
		t.Fatalf("expected translatable text")
	}
	if protected != `Top[[ASSTAG0]]Bottom[[ASSTAG1]]Word` {
		t.Errorf("protected text mismatch: got %q", protected)
	}
	if len(tags) != 2 || tags[0] != `\N` || tags[1] != `\h` {
		t.Errorf("tags mismatch: got %v", tags)
	}

	dlg := &Dialogue{
		Text:           raw,
		CleanText:      protected,
		Tags:           tags,
		IsTranslatable: true,
	}
	dlg.SetTranslatedText(`顶部[[ASSTAG0]]底部[[ASSTAG1]]词`)
	if dlg.Text != `顶部\N底部\h词` {
		t.Errorf("restored text mismatch: got %q, want %q", dlg.Text, `顶部\N底部\h词`)
	}

	plain, ok := StripASSTagsToPlainText(raw)
	if !ok || plain != "Top\nBottom Word" {
		t.Errorf("StripASSTagsToPlainText mismatch: got (%q, %v), want (\"Top\\nBottom Word\", true)", plain, ok)
	}
}

func TestParseASS_MultipleFormatDeclarationsInEvents(t *testing.T) {
	raw := `[Events]
Format: Start, End, VendorA, Text
Dialogue: 0:00:01.00,0:00:02.00,keep-a,Hello
Format: Start, End, VendorB, VendorA, Text
Dialogue: 0:00:03.00,0:00:04.00,keep-b,keep-a2,World
`
	file, errParse := ParseASS(raw)
	if errParse != nil {
		t.Fatalf("ParseASS failed: %v", errParse)
	}

	dialogues := file.GetDialogues()
	if len(dialogues) != 2 {
		t.Fatalf("expected 2 dialogues, got %d", len(dialogues))
	}

	composed := ComposeASS(file)
	expectedLine1 := "Dialogue: 0:00:01.00,0:00:02.00,keep-a,Hello"
	expectedLine2 := "Dialogue: 0:00:03.00,0:00:04.00,keep-b,keep-a2,World"

	if !strings.Contains(composed, expectedLine1) {
		t.Errorf("composed missing line 1:\n%s", composed)
	}
	if !strings.Contains(composed, expectedLine2) {
		t.Errorf("composed missing line 2:\n%s", composed)
	}
}

func TestDialogue_SignedDrawingParameter(t *testing.T) {
	raw := `{\p+1}m 0 0 l 10 10{\p0}Hello`
	protected, tags, isTranslatable := ExtractTags(raw)
	if !isTranslatable {
		t.Fatalf("expected translatable text for \\p+1")
	}
	if protected != "[[ASSTAG0]]Hello" {
		t.Errorf("protected mismatch: got %q, want '[[ASSTAG0]]Hello'", protected)
	}
	if len(tags) != 1 || tags[0] != "{\\p+1}m 0 0 l 10 10{\\p0}" {
		t.Errorf("expected 1 atomic tag with \\p+1, got: %v", tags)
	}

	plain, ok := StripASSTagsToPlainText(raw)
	if !ok || plain != "Hello" {
		t.Errorf("StripASSTagsToPlainText failed: got (%q, %v), want (\"Hello\", true)", plain, ok)
	}

	rawP0 := `{\p-0}Hello`
	_, _, isTranslatableP0 := ExtractTags(rawP0)
	if !isTranslatableP0 {
		t.Errorf("expected \\p-0 to keep text translatable")
	}

	// \p-1 turns off drawing mode in libass
	rawPMinus := `{\p1}m 0 0 l 10 10{\p-1}Hello`
	plainMinus, okMinus := StripASSTagsToPlainText(rawPMinus)
	if !okMinus || plainMinus != "Hello" {
		t.Errorf("expected \\p-1 to close drawing mode: got (%q, %v), want (\"Hello\", true)", plainMinus, okMinus)
	}

	// \p with whitespace like \p 1 turns on drawing mode
	rawPSpace := `{\p 1}m 0 0 l 10 10{\p0}Hello`
	plainSpace, okSpace := StripASSTagsToPlainText(rawPSpace)
	if !okSpace || plainSpace != "Hello" {
		t.Errorf("expected \\p 1 to enable drawing mode: got (%q, %v), want (\"Hello\", true)", plainSpace, okSpace)
	}

	// \p without argument turns off drawing mode (shorthand for \p0 in libass)
	rawPNoArg := `{\p1}m 0 0 l 10 10{\p}Hello`
	plainNoArg, okNoArg := StripASSTagsToPlainText(rawPNoArg)
	if !okNoArg || plainNoArg != "Hello" {
		t.Errorf("expected \\p without arg to close drawing mode: got (%q, %v), want (\"Hello\", true)", plainNoArg, okNoArg)
	}

	rawPInSameBlock := `{\p1\p}Hello`
	plainInSameBlock, okInSameBlock := StripASSTagsToPlainText(rawPInSameBlock)
	if !okInSameBlock || plainInSameBlock != "Hello" {
		t.Errorf("expected \\p1\\p to end in drawing mode off: got (%q, %v), want (\"Hello\", true)", plainInSameBlock, okInSameBlock)
	}

	// \ with whitespace before p like \ p1 turns on drawing mode
	rawPBackslashSpace := `{\ p1}m 0 0 l 10 10{\p0}Hello`
	plainBackslashSpace, okBackslashSpace := StripASSTagsToPlainText(rawPBackslashSpace)
	if !okBackslashSpace || plainBackslashSpace != "Hello" {
		t.Errorf("expected {\\ p1} to enable drawing mode: got (%q, %v), want (\"Hello\", true)", plainBackslashSpace, okBackslashSpace)
	}

	// \ with whitespace before q like \ q2 enables wrap style 2
	rawQBackslashSpace := `{\ q2}Hello\nworld`
	plainQBackslashSpace, okQBackslashSpace := StripASSTagsToPlainText(rawQBackslashSpace)
	if !okQBackslashSpace || plainQBackslashSpace != "Hello\nworld" {
		t.Errorf("expected {\\ q2} to enable wrap style 2: got (%q, %v), want (\"Hello\\nworld\", true)", plainQBackslashSpace, okQBackslashSpace)
	}

	// Parenthesized argument \p(1) turns on drawing mode
	rawPParen := `{\p(1)}m 0 0 l 10 10{\p0}Hello`
	plainParen, okParen := StripASSTagsToPlainText(rawPParen)
	if !okParen || plainParen != "Hello" {
		t.Errorf("expected {\\p(1)} to enable drawing mode: got (%q, %v), want (\"Hello\", true)", plainParen, okParen)
	}

	// Parenthesized argument with float/comma like \p(1.0) and \p(1,2)
	rawPFloat := `{\p(1.0)}m 0 0 l 10 10{\p0}Hello`
	plainFloat, okFloat := StripASSTagsToPlainText(rawPFloat)
	if !okFloat || plainFloat != "Hello" {
		t.Errorf("expected {\\p(1.0)} to enable drawing mode: got (%q, %v), want (\"Hello\", true)", plainFloat, okFloat)
	}

	rawPComma := `{\p(1,2)}m 0 0 l 10 10{\p0}Hello`
	plainComma, okComma := StripASSTagsToPlainText(rawPComma)
	if !okComma || plainComma != "Hello" {
		t.Errorf("expected {\\p(1,2)} to enable drawing mode: got (%q, %v), want (\"Hello\", true)", plainComma, okComma)
	}

	// Parenthesized argument \q(2) enables wrap style 2
	rawQParen := `{\q(2)}A\nB`
	plainQParen, okQParen := StripASSTagsToPlainText(rawQParen)
	if !okQParen || plainQParen != "A\nB" {
		t.Errorf("expected {\\q(2)} to enable wrap style 2: got (%q, %v), want (\"A\\nB\", true)", plainQParen, okQParen)
	}

	rawQFloat := `{\q(2.0)}Hello\nworld`
	plainQFloat, okQFloat := StripASSTagsToPlainText(rawQFloat)
	if !okQFloat || plainQFloat != "Hello\nworld" {
		t.Errorf("expected {\\q(2.0)} to enable wrap style 2: got (%q, %v), want (\"Hello\\nworld\", true)", plainQFloat, okQFloat)
	}

	// Priority of parenthesized argument over prefix: \p0(1) has priority 1 (drawing mode ON)
	rawPPriority := `{\p0(1)}m 0 0 l 10 10{\p0}Hello`
	plainPriority, okPriority := StripASSTagsToPlainText(rawPPriority)
	if !okPriority || plainPriority != "Hello" {
		t.Errorf("expected {\\p0(1)} to prioritize parenthesized 1: got (%q, %v), want (\"Hello\", true)", plainPriority, okPriority)
	}

	// Internal backslash inside parens: \p(0\p1) consumes whole parens with value 0 (drawing mode OFF)
	rawPInternalBs := `{\p(0\p1)}Hello`
	plainInternalBs, okInternalBs := StripASSTagsToPlainText(rawPInternalBs)
	if !okInternalBs || plainInternalBs != "Hello" {
		t.Errorf("expected {\\p(0\\p1)} to evaluate to 0 (off): got (%q, %v), want (\"Hello\", true)", plainInternalBs, okInternalBs)
	}

	// Backslash inside other commands parens like \q(0\p1) does not leak drawing command
	rawQInternalBs := `{\q(0\p1)}Hello`
	plainQInternalBs, okQInternalBs := StripASSTagsToPlainText(rawQInternalBs)
	if !okQInternalBs || plainQInternalBs != "Hello" {
		t.Errorf("expected {\\q(0\\p1)} not to leak \\p1: got (%q, %v), want (\"Hello\", true)", plainQInternalBs, okQInternalBs)
	}

	// Backslash inside drawing parens like \p(0\q2) does not leak wrap command
	rawPInternalQ := `{\p(0\q2)}A\nB`
	plainPInternalQ, okPInternalQ := StripASSTagsToPlainText(rawPInternalQ)
	if !okPInternalQ || plainPInternalQ != "A B" {
		t.Errorf("expected {\\p(0\\q2)} not to leak \\q2: got (%q, %v), want (\"A B\", true)", plainPInternalQ, okPInternalQ)
	}

	// Empty parens fallback to before parens: \p1() evaluates to 1 (drawing mode ON)
	rawPEmptyParen := `{\p1()}m 0 0 l 10 10{\p0}Hello`
	plainEmptyParen, okEmptyParen := StripASSTagsToPlainText(rawPEmptyParen)
	if !okEmptyParen || plainEmptyParen != "Hello" {
		t.Errorf("expected {\\p1()} to fallback to 1: got (%q, %v), want (\"Hello\", true)", plainEmptyParen, okEmptyParen)
	}

	// Leading comma in parens: \p(,1) uses first non-empty argument 1 (drawing mode ON)
	rawPLeadingComma := `{\p(,1)}m 0 0 l 10 10{\p0}Hello`
	plainLeadingComma, okLeadingComma := StripASSTagsToPlainText(rawPLeadingComma)
	if !okLeadingComma || plainLeadingComma != "Hello" {
		t.Errorf("expected {\\p(,1)} to use non-empty 1: got (%q, %v), want (\"Hello\", true)", plainLeadingComma, okLeadingComma)
	}

	// Empty parens fallback to before parens for wrap style: \q2() evaluates to 2 (newline)
	rawQEmptyParen := `{\q2()}A\nB`
	plainQEmptyParen, okQEmptyParen := StripASSTagsToPlainText(rawQEmptyParen)
	if !okQEmptyParen || plainQEmptyParen != "A\nB" {
		t.Errorf("expected {\\q2()} to fallback to 2: got (%q, %v), want (\"A\\nB\", true)", plainQEmptyParen, okQEmptyParen)
	}

	// Non-empty non-numeric argument inside parens evaluates to 0 in libass and does not skip to 2nd argument
	rawPNonNumericFirst := `{\p(foo,1)}Hello`
	plainNonNumericFirst, okNonNumericFirst := StripASSTagsToPlainText(rawPNonNumericFirst)
	if !okNonNumericFirst || plainNonNumericFirst != "Hello" {
		t.Errorf("expected {\\p(foo,1)} to evaluate to 0 (off): got (%q, %v), want (\"Hello\", true)", plainNonNumericFirst, okNonNumericFirst)
	}

	// Non-empty non-numeric argument inside parens overrides prefix
	rawPNonNumericOverride := `{\p1(foo)}Hello`
	plainNonNumericOverride, okNonNumericOverride := StripASSTagsToPlainText(rawPNonNumericOverride)
	if !okNonNumericOverride || plainNonNumericOverride != "Hello" {
		t.Errorf("expected {\\p1(foo)} to evaluate to 0 (off): got (%q, %v), want (\"Hello\", true)", plainNonNumericOverride, okNonNumericOverride)
	}

	// Non-empty non-numeric argument inside wrap style parens evaluates to 0 (default wrap style)
	rawQNonNumericFirst := `{\q(foo,2)}A\nB`
	plainQNonNumericFirst, okQNonNumericFirst := StripASSTagsToPlainText(rawQNonNumericFirst)
	if !okQNonNumericFirst || plainQNonNumericFirst != "A B" {
		t.Errorf("expected {\\q(foo,2)} to evaluate to 0 (space): got (%q, %v), want (\"A B\", true)", plainQNonNumericFirst, okQNonNumericFirst)
	}

	// Unclosed opening parenthesis terminated by closing brace }
	rawPUnclosedParen := `{\p(1}m 0 0 l 10 10{\p0}Hello`
	plainUnclosedParen, okUnclosedParen := StripASSTagsToPlainText(rawPUnclosedParen)
	if !okUnclosedParen || plainUnclosedParen != "Hello" {
		t.Errorf("expected {\\p(1} to enable drawing mode: got (%q, %v), want (\"Hello\", true)", plainUnclosedParen, okUnclosedParen)
	}

	rawQUnclosedParen := `{\q(2}A\nB`
	plainQUnclosedParen, okQUnclosedParen := StripASSTagsToPlainText(rawQUnclosedParen)
	if !okQUnclosedParen || plainQUnclosedParen != "A\nB" {
		t.Errorf("expected {\\q(2} to enable wrap style 2: got (%q, %v), want (\"A\\nB\", true)", plainQUnclosedParen, okQUnclosedParen)
	}

	// Unclosed parenthesis terminated by } across atomic drawing block preserves subsequent \q2
	rawUnclosedParenAcrossDrawing := `{\p(1}m 0 0 l 10 10{\p0\q2}Hello\nworld`
	plainAcrossDrawing, okAcrossDrawing := StripASSTagsToPlainText(rawUnclosedParenAcrossDrawing)
	if !okAcrossDrawing || plainAcrossDrawing != "Hello\nworld" {
		t.Errorf("expected unclosed paren to not swallow \\q2: got (%q, %v), want (\"Hello\\nworld\", true)", plainAcrossDrawing, okAcrossDrawing)
	}

	// Non-parenthesized non-numeric argument evaluates to 0 in libass (\pfoo -> 0 off)
	rawPNonNumericWithoutParen := `{\p1}m 0 0 l 10 10{\pfoo}Hello`
	plainPNonNumericWithoutParen, okPNonNumericWithoutParen := StripASSTagsToPlainText(rawPNonNumericWithoutParen)
	if !okPNonNumericWithoutParen || plainPNonNumericWithoutParen != "Hello" {
		t.Errorf("expected {\\pfoo} to turn off drawing mode: got (%q, %v), want (\"Hello\", true)", plainPNonNumericWithoutParen, okPNonNumericWithoutParen)
	}

	// Non-parenthesized non-numeric argument for wrap style resets to 0 (\qfoo -> 0 space)
	rawQNonNumericWithoutParen := `{\q2}A\nB{\qfoo}C\nD`
	plainQNonNumericWithoutParen, okQNonNumericWithoutParen := StripASSTagsToPlainText(rawQNonNumericWithoutParen)
	if !okQNonNumericWithoutParen || plainQNonNumericWithoutParen != "A\nBC D" {
		t.Errorf("expected {\\qfoo} to reset wrap style: got (%q, %v), want \"A\\nBC D\"", plainQNonNumericWithoutParen, okQNonNumericWithoutParen)
	}

	// \t(\p0) inside \t animation tag turns drawing mode OFF
	rawPInsideT := `{\p1}m 0 0 l 10 10{\t(\p0)}Hello`
	plainPInsideT, okPInsideT := StripASSTagsToPlainText(rawPInsideT)
	if !okPInsideT || plainPInsideT != "Hello" {
		t.Errorf("expected {\\t(\\p0)} to turn off drawing mode: got (%q, %v), want (\"Hello\", true)", plainPInsideT, okPInsideT)
	}

	// \t(\p1) inside \t animation tag turns drawing mode ON
	rawPInsideTOn := `{\t(\p1)}m 0 0 l 10 10{\p0}Hello`
	plainPInsideTOn, okPInsideTOn := StripASSTagsToPlainText(rawPInsideTOn)
	if !okPInsideTOn || plainPInsideTOn != "Hello" {
		t.Errorf("expected {\\t(\\p1)} to turn on drawing mode: got (%q, %v), want (\"Hello\", true)", plainPInsideTOn, okPInsideTOn)
	}

	// \t(\q2) inside \t animation tag sets wrap style 2
	rawQInsideT := `{\t(\q2)}A\nB`
	plainQInsideT, okQInsideT := StripASSTagsToPlainText(rawQInsideT)
	if !okQInsideT || plainQInsideT != "A\nB" {
		t.Errorf("expected {\\t(\\q2)} to set wrap style 2: got (%q, %v), want (\"A\\nB\", true)", plainQInsideT, okQInsideT)
	}

	// Non-numeric prefix on 4th argument in \t does not count as an extra argument before \
	rawT4thArgWithPrefix := `{\t(0,100,1,foo\p1)}m 0 0 l 10 10{\p0}Hello`
	plainT4thArgWithPrefix, okT4thArgWithPrefix := StripASSTagsToPlainText(rawT4thArgWithPrefix)
	if !okT4thArgWithPrefix || plainT4thArgWithPrefix != "Hello" {
		t.Errorf("expected {\\t(0,100,1,foo\\p1)} to execute \\p1: got (%q, %v), want (\"Hello\", true)", plainT4thArgWithPrefix, okT4thArgWithPrefix)
	}

	rawT4thArgWithPrefixQ := `{\t(0,100,1,foo\q2)}A\nB`
	plainT4thArgWithPrefixQ, okT4thArgWithPrefixQ := StripASSTagsToPlainText(rawT4thArgWithPrefixQ)
	if !okT4thArgWithPrefixQ || plainT4thArgWithPrefixQ != "A\nB" {
		t.Errorf("expected {\\t(0,100,1,foo\\q2)} to execute \\q2: got (%q, %v), want (\"A\\nB\", true)", plainT4thArgWithPrefixQ, okT4thArgWithPrefixQ)
	}

	// But 5th argument with prefix is invalid and ignored in libass (so \p1 is not executed, drawing coords remain text)
	rawT5thArgWithPrefix := `{\t(0,100,1,2,foo\p1)}m 0 0 l 10 10{\p0}Hello`
	plainT5thArgWithPrefix, okT5thArgWithPrefix := StripASSTagsToPlainText(rawT5thArgWithPrefix)
	if !okT5thArgWithPrefix || !strings.Contains(plainT5thArgWithPrefix, "m 0 0 l 10 10") {
		t.Errorf("expected invalid 5th argument \\t to not execute \\p1: got (%q, %v)", plainT5thArgWithPrefix, okT5thArgWithPrefix)
	}

	// Invalid \t with >= 4 commas before \ is ignored in libass
	rawTTooManyCommas := `{\t(0,100,1,2,\p1)}Hello`
	plainTTooManyCommas, okTTooManyCommas := StripASSTagsToPlainText(rawTTooManyCommas)
	if !okTTooManyCommas || plainTTooManyCommas != "Hello" {
		t.Errorf("expected invalid \\t with >=4 commas to be ignored: got (%q, %v), want (\"Hello\", true)", plainTTooManyCommas, okTTooManyCommas)
	}

	// Command prefix after t like \tfoo(...) validates arguments and ignores invalid 5th argument
	rawTFooInvalid := `{\tfoo(0,100,1,2,\p1)}Hello`
	plainTFooInvalid, okTFooInvalid := StripASSTagsToPlainText(rawTFooInvalid)
	if !okTFooInvalid || plainTFooInvalid != "Hello" {
		t.Errorf("expected invalid \\tfoo with 5 args to be ignored: got (%q, %v), want (\"Hello\", true)", plainTFooInvalid, okTFooInvalid)
	}

	rawTFooInvalidQ := `{\tfoo(0,100,1,2,\q2)}A\nB`
	plainTFooInvalidQ, okTFooInvalidQ := StripASSTagsToPlainText(rawTFooInvalidQ)
	if !okTFooInvalidQ || plainTFooInvalidQ != "A B" {
		t.Errorf("expected invalid \\tfoo with 5 args to be ignored: got (%q, %v), want (\"A B\", true)", plainTFooInvalidQ, okTFooInvalidQ)
	}

	rawTFooValid := `{\tfoo(\p1)}m 0 0 l 10 10{\p0}Hello`
	plainTFooValid, okTFooValid := StripASSTagsToPlainText(rawTFooValid)
	if !okTFooValid || plainTFooValid != "Hello" {
		t.Errorf("expected valid \\tfoo to execute \\p1: got (%q, %v), want (\"Hello\", true)", plainTFooValid, okTFooValid)
	}

	// Closing paren in \t prefix outside \t does not bypass argument validation
	rawTParenInPrefix := `{\t)(0,100,1,2,\p1)}Hello`
	plainTParenInPrefix, okTParenInPrefix := StripASSTagsToPlainText(rawTParenInPrefix)
	if !okTParenInPrefix || plainTParenInPrefix != "Hello" {
		t.Errorf("expected \\t)(0,100,1,2,\\p1) to be rejected as invalid: got (%q, %v), want (\"Hello\", true)", plainTParenInPrefix, okTParenInPrefix)
	}

	rawTParenInPrefixQ := `{\t)(0,100,1,2,\q2)}A\nB`
	plainTParenInPrefixQ, okTParenInPrefixQ := StripASSTagsToPlainText(rawTParenInPrefixQ)
	if !okTParenInPrefixQ || plainTParenInPrefixQ != "A B" {
		t.Errorf("expected \\t)(0,100,1,2,\\q2) to be rejected as invalid: got (%q, %v), want (\"A B\", true)", plainTParenInPrefixQ, okTParenInPrefixQ)
	}

	// \t transform ends at the first closing parenthesis ')'
	rawTNestedParenBoundary := `{\t(\t(\p0)\p)(1)}m 0 0 l 10 10{\p0}Hello`
	plainTNestedParenBoundary, okTNestedParenBoundary := StripASSTagsToPlainText(rawTNestedParenBoundary)
	if !okTNestedParenBoundary || plainTNestedParenBoundary != "Hello" {
		t.Errorf("expected \\t to end at first ')' and execute \\p)(1): got (%q, %v), want (\"Hello\", true)", plainTNestedParenBoundary, okTNestedParenBoundary)
	}

	rawTNestedParenBoundaryQ := `{\t(\t(\p0)\q)(2)}A\nB`
	plainTNestedParenBoundaryQ, okTNestedParenBoundaryQ := StripASSTagsToPlainText(rawTNestedParenBoundaryQ)
	if !okTNestedParenBoundaryQ || plainTNestedParenBoundaryQ != "A\nB" {
		t.Errorf("expected \\t to end at first ')' and execute \\q)(2): got (%q, %v), want (\"A\\nB\", true)", plainTNestedParenBoundaryQ, okTNestedParenBoundaryQ)
	}

	// Argument paren closure ')' or invalid \t skip ')' ends transform scope
	rawTArgParenEndsT := `{\t(\p(0)\p)(1)}m 0 0 l 10 10{\p0}Hello`
	plainTArgParenEndsT, okTArgParenEndsT := StripASSTagsToPlainText(rawTArgParenEndsT)
	if !okTArgParenEndsT || plainTArgParenEndsT != "Hello" {
		t.Errorf("expected \\p(0) paren to end \\t scope: got (%q, %v), want (\"Hello\", true)", plainTArgParenEndsT, okTArgParenEndsT)
	}

	rawTArgParenEndsTQ := `{\t(\p(0)\q)(2)}A\nB`
	plainTArgParenEndsTQ, okTArgParenEndsTQ := StripASSTagsToPlainText(rawTArgParenEndsTQ)
	if !okTArgParenEndsTQ || plainTArgParenEndsTQ != "A\nB" {
		t.Errorf("expected \\p(0) paren to end \\t scope: got (%q, %v), want (\"A\\nB\", true)", plainTArgParenEndsTQ, okTArgParenEndsTQ)
	}

	rawTInvalidNestedEndsT := `{\t(\t(0,1,2,3,\p0)\p)(1)}m 0 0 l 10 10{\p0}Hello`
	plainTInvalidNestedEndsT, okTInvalidNestedEndsT := StripASSTagsToPlainText(rawTInvalidNestedEndsT)
	if !okTInvalidNestedEndsT || plainTInvalidNestedEndsT != "Hello" {
		t.Errorf("expected invalid nested \\t skip to end \\t scope: got (%q, %v), want (\"Hello\", true)", plainTInvalidNestedEndsT, okTInvalidNestedEndsT)
	}

	// Bare \q in drawing data between override tags is not an override command
	rawDrawingWithBareQ := `{\p1}m 0 0 l 10 10\q2{\p0}A\nB`
	plainDrawingWithBareQ, okDrawingWithBareQ := StripASSTagsToPlainText(rawDrawingWithBareQ)
	if !okDrawingWithBareQ || plainDrawingWithBareQ != "A B" {
		t.Errorf("expected bare \\q2 in drawing data to not set wrap style 2: got (%q, %v), want (\"A B\", true)", plainDrawingWithBareQ, okDrawingWithBareQ)
	}

	// Oversized integers saturate to int32 range in libass
	rawPOversized := `{\p9223372036854775808}m 0 0 l 10 10{\p0}Hello`
	plainPOversized, okPOversized := StripASSTagsToPlainText(rawPOversized)
	if !okPOversized || plainPOversized != "Hello" {
		t.Errorf("expected positive overflow \\p to turn on drawing mode: got (%q, %v), want (\"Hello\", true)", plainPOversized, okPOversized)
	}

	rawPMinusOversized := `{\p-9223372036854775808}Hello`
	plainPMinusOversized, okPMinusOversized := StripASSTagsToPlainText(rawPMinusOversized)
	if !okPMinusOversized || plainPMinusOversized != "Hello" {
		t.Errorf("expected negative overflow \\p to stay in text mode: got (%q, %v), want (\"Hello\", true)", plainPMinusOversized, okPMinusOversized)
	}

	rawQOversized := `{\q9223372036854775808}A\nB`
	plainQOversized, okQOversized := StripASSTagsToPlainText(rawQOversized, 2)
	if !okQOversized || plainQOversized != "A\nB" {
		t.Errorf("expected overflow \\q to reset to WrapStyle 2: got (%q, %v), want (\"A\\nB\", true)", plainQOversized, okQOversized)
	}

	// Unicode whitespace like \u00a0 is non-ASCII and must NOT be treated as whitespace in arguments
	rawPUnicodeSpace := "{\\p\u00a01}Visible"
	plainPUnicodeSpace, okPUnicodeSpace := StripASSTagsToPlainText(rawPUnicodeSpace)
	if !okPUnicodeSpace || plainPUnicodeSpace != "Visible" {
		t.Errorf("expected \\p\\u00a01 to evaluate to 0 (text mode): got (%q, %v), want (\"Visible\", true)", plainPUnicodeSpace, okPUnicodeSpace)
	}

	rawQUnicodeSpace := "{\\q\u00a02}First\\nSecond"
	plainQUnicodeSpace, okQUnicodeSpace := StripASSTagsToPlainText(rawQUnicodeSpace)
	if !okQUnicodeSpace || plainQUnicodeSpace != "First Second" {
		t.Errorf("expected \\q\\u00a02 to evaluate to 0 (space): got (%q, %v), want (\"First Second\", true)", plainQUnicodeSpace, okQUnicodeSpace)
	}

	// C whitespace characters (\v, \f) are recognized as leading whitespace in integer arguments
	rawPV := "{\\p\v1}m 0 0 l 10 10{\\p0}Visible"
	plainPV, okPV := StripASSTagsToPlainText(rawPV)
	if !okPV || plainPV != "Visible" {
		t.Errorf("expected \\p\\v1 to evaluate to 1 (drawing mode ON): got (%q, %v), want (\"Visible\", true)", plainPV, okPV)
	}

	rawPF := "{\\p\f1}m 0 0 l 10 10{\\p0}Visible"
	plainPF, okPF := StripASSTagsToPlainText(rawPF)
	if !okPF || plainPF != "Visible" {
		t.Errorf("expected \\p\\f1 to evaluate to 1 (drawing mode ON): got (%q, %v), want (\"Visible\", true)", plainPF, okPF)
	}

	// Delimiter trimming only trims spaces and tabs, not \\r; \\r is non-empty so it evaluates to 0 and does not skip to 2nd argument
	rawPR := "{\\p(\r,1)}Visible"
	plainPR, okPR := StripASSTagsToPlainText(rawPR)
	if !okPR || plainPR != "Visible" {
		t.Errorf("expected \\p(\\r,1) to evaluate to 0: got (%q, %v), want (\"Visible\", true)", plainPR, okPR)
	}

	// Empty command name before parenthesis (e.g. \() does not swallow subsequent commands
	rawEmptyCmdP1 := `{\(\p1)}m 0 0 l 10 10{\p0}Hello`
	plainEmptyCmdP1, okEmptyCmdP1 := StripASSTagsToPlainText(rawEmptyCmdP1)
	if !okEmptyCmdP1 || plainEmptyCmdP1 != "Hello" {
		t.Errorf("expected \\(\\p1) to execute \\p1: got (%q, %v), want (\"Hello\", true)", plainEmptyCmdP1, okEmptyCmdP1)
	}

	rawEmptyCmdP0 := `{\p1}m 0 0 l 10 10{\(\p0)}Hello`
	plainEmptyCmdP0, okEmptyCmdP0 := StripASSTagsToPlainText(rawEmptyCmdP0)
	if !okEmptyCmdP0 || plainEmptyCmdP0 != "Hello" {
		t.Errorf("expected \\(\\p0) to execute \\p0: got (%q, %v), want (\"Hello\", true)", plainEmptyCmdP0, okEmptyCmdP0)
	}

	rawEmptyCmdQ2 := `{\(\q2)}A\nB`
	plainEmptyCmdQ2, okEmptyCmdQ2 := StripASSTagsToPlainText(rawEmptyCmdQ2)
	if !okEmptyCmdQ2 || plainEmptyCmdQ2 != "A\nB" {
		t.Errorf("expected \\(\\q2) to execute \\q2: got (%q, %v), want (\"A\\nB\", true)", plainEmptyCmdQ2, okEmptyCmdQ2)
	}

	// Commands starting with digits (e.g. \1c, \1a) consume parenthesized arguments without leaking internal \p or \q
	rawDigitCmdP1 := `{\1c(&HFF0000&\p1)}Hello`
	plainDigitCmdP1, okDigitCmdP1 := StripASSTagsToPlainText(rawDigitCmdP1)
	if !okDigitCmdP1 || plainDigitCmdP1 != "Hello" {
		t.Errorf("expected \\1c(...) to consume argument without executing internal \\p1: got (%q, %v), want (\"Hello\", true)", plainDigitCmdP1, okDigitCmdP1)
	}

	rawDigitCmdP0 := `{\p1}m 0 0{\1c(\p0)}l 10 10{\p0}Hello`
	plainDigitCmdP0, okDigitCmdP0 := StripASSTagsToPlainText(rawDigitCmdP0)
	if !okDigitCmdP0 || plainDigitCmdP0 != "Hello" {
		t.Errorf("expected \\1c(...) to consume argument without executing internal \\p0: got (%q, %v), want (\"Hello\", true)", plainDigitCmdP0, okDigitCmdP0)
	}

	rawDigitCmdQ2 := `{\1a(\q2)}A\nB`
	plainDigitCmdQ2, okDigitCmdQ2 := StripASSTagsToPlainText(rawDigitCmdQ2)
	if !okDigitCmdQ2 || plainDigitCmdQ2 != "A B" {
		t.Errorf("expected \\1a(...) to consume argument without executing internal \\q2: got (%q, %v), want (\"A B\", true)", plainDigitCmdQ2, okDigitCmdQ2)
	}

	// Command \) outside \t consumes parenthesized arguments without leaking internal \p or \q
	rawParenCmdP1 := `{\)(\p1)}Hello`
	plainParenCmdP1, okParenCmdP1 := StripASSTagsToPlainText(rawParenCmdP1)
	if !okParenCmdP1 || plainParenCmdP1 != "Hello" {
		t.Errorf("expected \\)(...) to consume argument without executing internal \\p1: got (%q, %v), want (\"Hello\", true)", plainParenCmdP1, okParenCmdP1)
	}

	rawParenCmdQ2 := `{\)(\q2)}A\nB`
	plainParenCmdQ2, okParenCmdQ2 := StripASSTagsToPlainText(rawParenCmdQ2)
	if !okParenCmdQ2 || plainParenCmdQ2 != "A B" {
		t.Errorf("expected \\)(...) to consume argument without executing internal \\q2: got (%q, %v), want (\"A B\", true)", plainParenCmdQ2, okParenCmdQ2)
	}

	rawParenCmdP0 := `{\p1}m 0 0{\)(\p0)}l 10 10{\p0}Hello`
	plainParenCmdP0, okParenCmdP0 := StripASSTagsToPlainText(rawParenCmdP0)
	if !okParenCmdP0 || plainParenCmdP0 != "Hello" {
		t.Errorf("expected \\)(...) to consume argument without executing internal \\p0: got (%q, %v), want (\"Hello\", true)", plainParenCmdP0, okParenCmdP0)
	}

	// Closing parenthesis before parenthesized arguments when not inside \\t does not terminate argument scan
	rawPClosingParenBeforeArgs := `{\p)(1)}m 0 0 l 10 10{\p0}Hello`
	plainPClosingParenBeforeArgs, okPClosingParenBeforeArgs := StripASSTagsToPlainText(rawPClosingParenBeforeArgs)
	if !okPClosingParenBeforeArgs || plainPClosingParenBeforeArgs != "Hello" {
		t.Errorf("expected \\p)(1) to evaluate to 1: got (%q, %v), want (\"Hello\", true)", plainPClosingParenBeforeArgs, okPClosingParenBeforeArgs)
	}

	rawQClosingParenBeforeArgs := `{\q)(2)}A\nB`
	plainQClosingParenBeforeArgs, okQClosingParenBeforeArgs := StripASSTagsToPlainText(rawQClosingParenBeforeArgs)
	if !okQClosingParenBeforeArgs || plainQClosingParenBeforeArgs != "A\nB" {
		t.Errorf("expected \\q)(2) to evaluate to 2: got (%q, %v), want (\"A\\nB\", true)", plainQClosingParenBeforeArgs, okQClosingParenBeforeArgs)
	}

	// Empty arguments in \t are skipped in libass (e.g. \t(,,,,\\p0) is valid)
	rawTEmptyCommas := `{\p1}m 0 0 l 10 10{\t(,,,,\p0)}Hello`
	plainTEmptyCommas, okTEmptyCommas := StripASSTagsToPlainText(rawTEmptyCommas)
	if !okTEmptyCommas || plainTEmptyCommas != "Hello" {
		t.Errorf("expected empty arguments in \\t to be valid: got (%q, %v), want (\"Hello\", true)", plainTEmptyCommas, okTEmptyCommas)
	}

	// Nested \t beyond former depth limit correctly executes inner \p0
	rawTNestedP0 := `{\p1}m 0 0 l 10 10{` + strings.Repeat(`\t(`, 5) + `\p0}Hello`
	plainTNestedP0, okTNestedP0 := StripASSTagsToPlainText(rawTNestedP0)
	if !okTNestedP0 || plainTNestedP0 != "Hello" {
		t.Errorf("expected nested \\t to execute \\p0: got (%q, %v), want (\"Hello\", true)", plainTNestedP0, okTNestedP0)
	}

	// Outer invalid \t ending at first ')' does not leak invalid state to following commands
	rawTNestedInvalid := `{\p1\t(0,100,1,2,\t(\q0)\p0)}Hello`
	plainTNestedInvalid, okTNestedInvalid := StripASSTagsToPlainText(rawTNestedInvalid)
	if !okTNestedInvalid || plainTNestedInvalid != "Hello" {
		t.Errorf("expected outer invalid \\t not to leak state: got (%q, %v), want (\"Hello\", true)", plainTNestedInvalid, okTNestedInvalid)
	}

	// Linear performance for 800,000 unclosed braces
	rawManyBraces := strings.Repeat("{", 800000)
	_, _, isTransManyBraces := ExtractTags(rawManyBraces)
	_ = isTransManyBraces

	// Linear performance for 64,000 nested \t(
	rawT64k := "{" + strings.Repeat(`\t(`, 64000) + `\p0}Hello`
	plainT64k, okT64k := StripASSTagsToPlainText(rawT64k)
	if !okT64k || plainT64k != "Hello" {
		t.Errorf("expected 64,000 nested \\t to execute in linear time and return Hello: got (%q, %v)", plainT64k, okT64k)
	}

	// Commands after invalid \t within the same tag block execute normally (closing paren exits \t scope)
	rawTInvalidThenP0 := `{\p1\t(0,100,1,2,\q2)\p0}Hello`
	plainTInvalidThenP0, okTInvalidThenP0 := StripASSTagsToPlainText(rawTInvalidThenP0)
	if !okTInvalidThenP0 || plainTInvalidThenP0 != "Hello" {
		t.Errorf("expected \\p0 after invalid \\t to execute: got (%q, %v), want (\"Hello\", true)", plainTInvalidThenP0, okTInvalidThenP0)
	}

	rawTInvalidThenQ2 := `{\t(0,100,1,2,\q0)\q2}A\nB`
	plainTInvalidThenQ2, okTInvalidThenQ2 := StripASSTagsToPlainText(rawTInvalidThenQ2)
	if !okTInvalidThenQ2 || plainTInvalidThenQ2 != "A\nB" {
		t.Errorf("expected \\q2 after invalid \\t to execute: got (%q, %v), want (\"A\\nB\", true)", plainTInvalidThenQ2, okTInvalidThenQ2)
	}

	// Linear performance scanning consecutive layout escapes
	rawManyN := strings.Repeat(`\N`, 32000) + "Hello"
	_, _, isTransManyN := ExtractTags(rawManyN)
	if !isTransManyN {
		t.Errorf("expected translatable for many layout escapes")
	}

	// Nested \t correctly executes inner \q2
	rawTNestedQ2 := `{` + strings.Repeat(`\t(`, 5) + `\q2)}A\nB`
	plainTNestedQ2, okTNestedQ2 := StripASSTagsToPlainText(rawTNestedQ2)
	if !okTNestedQ2 || plainTNestedQ2 != "A\nB" {
		t.Errorf("expected nested \\t to execute \\q2: got (%q, %v), want (\"A\\nB\", true)", plainTNestedQ2, okTNestedQ2)
	}

	// Execution order of \t and following commands in the same tag block
	rawTP1P0 := `{\t(\p1)\p0}Hello`
	plainTP1P0, okTP1P0 := StripASSTagsToPlainText(rawTP1P0)
	if !okTP1P0 || plainTP1P0 != "Hello" {
		t.Errorf("expected {\\t(\\p1)\\p0} to leave drawing mode off: got (%q, %v), want (\"Hello\", true)", plainTP1P0, okTP1P0)
	}

	rawTP0P1 := `{\t(\p0)\p1}m 0 0 l 10 10{\p0}Hello`
	plainTP0P1, okTP0P1 := StripASSTagsToPlainText(rawTP0P1)
	if !okTP0P1 || plainTP0P1 != "Hello" {
		t.Errorf("expected {\\t(\\p0)\\p1} to turn drawing mode on: got (%q, %v), want (\"Hello\", true)", plainTP0P1, okTP0P1)
	}

	rawTQ2Q0 := `{\t(\q2)\q0}A\nB`
	plainTQ2Q0, okTQ2Q0 := StripASSTagsToPlainText(rawTQ2Q0)
	if !okTQ2Q0 || plainTQ2Q0 != "A B" {
		t.Errorf("expected {\\t(\\q2)\\q0} to leave wrap style 0 (space): got (%q, %v), want (\"A B\", true)", plainTQ2Q0, okTQ2Q0)
	}

	rawTQ0Q2 := `{\t(\q0)\q2}A\nB`
	plainTQ0Q2, okTQ0Q2 := StripASSTagsToPlainText(rawTQ0Q2)
	if !okTQ0Q2 || plainTQ0Q2 != "A\nB" {
		t.Errorf("expected {\\t(\\q0)\\q2} to leave wrap style 2 (newline): got (%q, %v), want (\"A\\nB\", true)", plainTQ0Q2, okTQ0Q2)
	}

	// Deeply nested \t does not cause memory explosion or stack overflow (linear performance test)
	rawTDeep := "{" + strings.Repeat(`\t(`, 32000) + `\p0}Hello`
	_, _, isTransDeep := ExtractTags(rawTDeep)
	if !isTransDeep {
		t.Errorf("expected text after deeply nested \\t to remain translatable")
	}

	// Priority of parenthesized argument for wrap style: \q0(2) has priority 2 (newline)
	rawQPriority := `{\q0(2)}A\nB`
	plainQPriority, okQPriority := StripASSTagsToPlainText(rawQPriority)
	if !okQPriority || plainQPriority != "A\nB" {
		t.Errorf("expected {\\q0(2)} to prioritize parenthesized 2: got (%q, %v), want (\"A\\nB\", true)", plainQPriority, okQPriority)
	}

	// Case sensitivity: uppercase \P1 and \Q2 are unknown tags in libass, not drawing/wrap commands!
	rawUpperP := `{\P1}Hello`
	plainUpperP, okUpperP := StripASSTagsToPlainText(rawUpperP)
	if !okUpperP || plainUpperP != "Hello" {
		t.Errorf("expected {\\P1} to not trigger drawing mode: got (%q, %v), want (\"Hello\", true)", plainUpperP, okUpperP)
	}

	rawUpperQ := `{\Q2}A\nB`
	plainUpperQ, okUpperQ := StripASSTagsToPlainText(rawUpperQ)
	if !okUpperQ || plainUpperQ != "A B" {
		t.Errorf("expected {\\Q2} to not trigger wrap style 2: got (%q, %v), want (\"A B\", true)", plainUpperQ, okUpperQ)
	}

	// Avoid false positive matching of \pos or \pbo
	rawPos := `{\pos(100,200)}Hello`
	plainPos, okPos := StripASSTagsToPlainText(rawPos)
	if !okPos || plainPos != "Hello" {
		t.Errorf("expected \\pos not to trigger drawing mode: got (%q, %v), want (\"Hello\", true)", plainPos, okPos)
	}
}

func TestExtractTags_EscapedBraces(t *testing.T) {
	raw := `\{Hello\}`
	protected, tags, isTranslatable := ExtractTags(raw)
	if !isTranslatable {
		t.Fatalf("escaped braces should be translatable text")
	}
	if len(tags) != 0 {
		t.Errorf("escaped braces should not be treated as tags, got tags: %v", tags)
	}
	if protected != `\{Hello\}` {
		t.Errorf("protected text mismatch: got %q, want %q", protected, `\{Hello\}`)
	}

	plain, ok := StripASSTagsToPlainText(raw)
	if !ok || plain != "{Hello}" {
		t.Errorf("StripASSTagsToPlainText failed: got (%q, %v), want (\"{Hello}\", true)", plain, ok)
	}

	// Double backslash preceding brace: in ASS, \{ is an escaped brace, preceding \ is literal \
	rawDouble := `\\{Hello}`
	_, tagsDouble, isTransDouble := ExtractTags(rawDouble)
	if !isTransDouble {
		t.Fatalf("expected translatable for double backslash brace")
	}
	if len(tagsDouble) != 0 {
		t.Errorf("expected no tags for double backslash brace, got: %v", tagsDouble)
	}

	// A\\NB: A\ followed by newline \N followed by B
	rawANB := `A\\NB`
	_, tagsANB, isTransANB := ExtractTags(rawANB)
	if !isTransANB {
		t.Fatalf("expected translatable for A\\\\NB")
	}
	if len(tagsANB) != 1 || tagsANB[0] != `\N` {
		t.Errorf("expected \\N to be captured as layout tag, got: %v", tagsANB)
	}
	plainANB, okANB := StripASSTagsToPlainText(rawANB)
	if !okANB || plainANB != "A\\\nB" {
		t.Errorf("expected A\\\\\\nB: got (%q, %v)", plainANB, okANB)
	}
}

func TestExtractTags_UnclosedBraceWithLayout(t *testing.T) {
	raw := `Hello {literal\Nworld`
	protected, tags, isTranslatable := ExtractTags(raw)
	if !isTranslatable {
		t.Fatalf("unclosed brace text should be translatable")
	}
	if len(tags) != 1 || tags[0] != `\N` {
		t.Errorf("expected \\N to be captured as layout tag despite unclosed brace, got tags: %v", tags)
	}
	if !strings.Contains(protected, "[[ASSTAG0]]") {
		t.Errorf("protected text missing tag placeholder: %q", protected)
	}

	plain, ok := StripASSTagsToPlainText(raw)
	if !ok || plain != "Hello {literal\nworld" {
		t.Errorf("StripASSTagsToPlainText failed: got (%q, %v), want (\"Hello {literal\\nworld\", true)", plain, ok)
	}
}

func TestStripASSTagsToPlainText_SoftAndHardBreaks(t *testing.T) {
	// Soft break \n in standard wrap styles renders as space in plain text
	soft := `Hello\nworld`
	plainSoft, okSoft := StripASSTagsToPlainText(soft)
	if !okSoft || plainSoft != "Hello world" {
		t.Errorf("expected soft break to become space: got %q", plainSoft)
	}

	// Hard break \N always forces newline
	hard := `Hello\Nworld`
	plainHard, okHard := StripASSTagsToPlainText(hard)
	if !okHard || plainHard != "Hello\nworld" {
		t.Errorf("expected hard break to become newline: got %q", plainHard)
	}

	// Inline \q2 activates wrap style 2 where \n forces newline
	q2 := `{\q2}Hello\nworld`
	plainQ2, okQ2 := StripASSTagsToPlainText(q2)
	if !okQ2 || plainQ2 != "Hello\nworld" {
		t.Errorf("expected \\q2 soft break to become newline: got %q", plainQ2)
	}

	// Script-level WrapStyle: 2 causes \n to force newline
	plainWrap2, okWrap2 := StripASSTagsToPlainText(`Hello\nworld`, 2)
	if !okWrap2 || plainWrap2 != "Hello\nworld" {
		t.Errorf("expected defaultWrapStyle 2 soft break to become newline: got %q", plainWrap2)
	}

	// \q resets to script-level default
	qReset := `{\q2}A\nB{\q}C\nD`
	plainQReset, okQReset := StripASSTagsToPlainText(qReset)
	if !okQReset || plainQReset != "A\nBC D" {
		t.Errorf("expected \\q to reset wrap style: got %q, want \"A\\nBC D\"", plainQReset)
	}

	// \q9 (out of range) resets to script-level default
	qInvalidReset := `{\q2}A\nB{\q9}C\nD`
	plainQInvReset, okQInvReset := StripASSTagsToPlainText(qInvalidReset)
	if !okQInvReset || plainQInvReset != "A\nBC D" {
		t.Errorf("expected \\q9 to reset wrap style: got %q, want \"A\\nBC D\"", plainQInvReset)
	}
}

func TestExtractTags_ClosingBraceWithBackslash(t *testing.T) {
	// First } always closes the override tag in libass even if preceded by backslash
	raw := `{\i1\}Hello{\i0}`
	protected, tags, isTranslatable := ExtractTags(raw)
	if !isTranslatable {
		t.Fatalf("expected translatable for {\\i1\\}Hello{\\i0}")
	}
	if len(tags) != 2 || tags[0] != `{\i1\}` || tags[1] != `{\i0}` {
		t.Errorf("expected 2 tags {\\i1\\} and {\\i0}, got: %v", tags)
	}
	if protected != "[[ASSTAG0]]Hello[[ASSTAG1]]" {
		t.Errorf("protected mismatch: got %q, want '[[ASSTAG0]]Hello[[ASSTAG1]]'", protected)
	}

	plain, ok := StripASSTagsToPlainText(raw)
	if !ok || plain != "Hello" {
		t.Errorf("expected plain text 'Hello', got (%q, %v)", plain, ok)
	}
}

func TestDialogue_EscapesLiteralBracesInTranslatedText(t *testing.T) {
	d := &Dialogue{
		Text:           "Hello",
		CleanText:      "Hello",
		IsTranslatable: true,
	}
	d.SetTranslatedText("{Bonjour}")
	if d.Text != `\{Bonjour\}` {
		t.Errorf("expected literal braces to be escaped, got %q, want %q", d.Text, `\{Bonjour\}`)
	}

	plain, ok := StripASSTagsToPlainText(d.Text)
	if !ok || plain != "{Bonjour}" {
		t.Errorf("StripASSTagsToPlainText failed: got (%q, %v), want (\"{Bonjour}\", true)", plain, ok)
	}
}

func TestDialogue_AlreadyEscapedBracesNotDoubleEscaped(t *testing.T) {
	raw := `Say \{Hello\}`
	d := &Dialogue{
		Text:           raw,
		CleanText:      raw,
		IsTranslatable: true,
	}
	// Model returns already-escaped braces
	d.SetTranslatedText(raw)
	if d.Text != raw {
		t.Errorf("already-escaped braces were double escaped: got %q, want %q", d.Text, raw)
	}

	plain, ok := StripASSTagsToPlainText(d.Text)
	if !ok || plain != "Say {Hello}" {
		t.Errorf("expected plain text 'Say {Hello}', got (%q, %v)", plain, ok)
	}
}

func TestDialogue_DrawingWithEscapedBraceInternal(t *testing.T) {
	raw := `{\p1}m 0 0 l 10 10\{\p0}Hello`
	plain, ok := StripASSTagsToPlainText(raw)
	if !ok || plain != "Hello" {
		t.Errorf("expected drawing mode to end at {\\p0} even if preceded by backslash: got (%q, %v), want (\"Hello\", true)", plain, ok)
	}
}

func TestFile_GetWrapStyle(t *testing.T) {
	tests := []struct {
		content  string
		expected int
	}{
		{"[Script Info]\nWrapStyle: 2\n", 2},
		{"[Script Info]\nWrapStyle:2\n", 2},
		{"[Script Info]\nWrapStyle:  2\n", 2},
		{"[Script Info]\n; WrapStyle: 2\n", 0},
		{"[Script Info]\nTitle: Test\n", 0},
	}

	for _, tc := range tests {
		file, err := ParseASS(tc.content)
		if err != nil {
			t.Fatalf("ParseASS failed: %v", err)
		}
		if got := file.GetWrapStyle(); got != tc.expected {
			t.Errorf("GetWrapStyle(%q) = %d, want %d", tc.content, got, tc.expected)
		}
	}
}
